name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Hugo
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.108.0'  # Versi Hugo yang diinginkan

    # Build the Hugo site
    - name: Build Hugo site
      run: hugo

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Direktori tempat hasil build Hugo disimpan
